002 view job spec each job
TaylorJCrawford/the-it-crowd-api pull request #14
Opened 2023-11-16 15:26 UTC by dcorry586

2023-11-16 15:40 UTC, dmkainos commented on src/main/java/org/kainos/ea/cli/JobSpec.java
> +    private int jobSpecID;
There is an issue here with JobSpec, should it not be jobSpecId?

2023-11-16 15:41 UTC, dmkainos commented on src/main/java/org/kainos/ea/db/JobSpecDao.java
> +                System.out.println("in side while loop: " + jobSpec.getJobSpecName());
Do we need this system print ln?

2023-11-16 15:43 UTC, dmkainos commented on src/main/java/org/kainos/ea/resources/JobSpecController.java
> +        } catch (JobSpecsNotFoundException | SQLException e) {
Should the catch errors not beconsistent with the /job-specs/{id} below?

2023-11-20 14:31 UTC, dcorry586 commented on .github/workflows/weekday-evening-api-audit.yml
put this in instead:

change cron to "0 22 * * 1-5"

run: mvn verify -DskipTests

2023-11-20 14:31 UTC, dcorry586 commented on sql-scripts/create-job-roles.sql
add jobSpecUrl field into insert query.

2023-11-20 14:31 UTC, dcorry586 commented on src/main/java/org/kainos/ea/api/JobRequest.java
remove class as job model has the Sharepoint link field.

2023-11-20 14:31 UTC, dcorry586 commented on src/main/java/org/kainos/ea/cli/Job.java
move constructor to top

2023-11-20 14:31 UTC, dcorry586 commented on src/main/java/org/kainos/ea/client/JobSpecsNotFoundException.java
remove exception.

2023-11-20 14:31 UTC, dcorry586 commented on src/main/java/org/kainos/ea/controller/JobController.java
>        System.err.println(e);
e.getMessage();

2023-11-20 14:31 UTC, dcorry586 commented on src/main/java/org/kainos/ea/controller/JobController.java
>        System.err.println(e);
e.getMessage();

2023-11-20 14:31 UTC, dcorry586 commented on src/main/java/org/kainos/ea/controller/JobController.java
> +    catch(SQLException e){
catch on same line as bracket. 

e.getMessage();

2023-11-20 14:31 UTC, dcorry586 commented on src/main/java/org/kainos/ea/db/DatabaseConnector.java
> +    System.out.println("user env: " + user);
remove print user env

2023-11-20 14:31 UTC, dcorry586 commented on src/test/java/org/kainos/ea/integration/JobIntegrationTest.java
> +    System.out.println("LOGGING HOST --> " + host);
remove logging host

2023-11-20 14:31 UTC, dcorry586 commented on src/test/java/org/kainos/ea/integration/JobIntegrationTest.java
> +    int expectedId = 1;
remove variable and use value 1

2023-11-20 14:31 UTC, dcorry586 commented on src/test/java/org/kainos/ea/integration/JobSpecIntegrationTest.java
job spec class redundant - remove.

2023-11-20 14:31 UTC, dcorry586 commented on src/test/java/org/kainos/ea/service/JobServiceTest.java
> +        Job job2 = new Job(1, "Test Engineer", "https://www.something.com");
2 instead of 1

2023-11-20 14:31 UTC, dcorry586 commented on src/test/java/org/kainos/ea/service/JobServiceTest.java
> +        Job job = new Job(id, "Software Engineer",  "https://www.aye.co.uk/");
sample instead of aye ! :|

2023-11-20 14:31 UTC, dcorry586 commented on src/test/java/org/kainos/ea/service/JobSpecServiceTest.java
remove!!!

2023-11-21 09:59 UTC, dmkainos requested changes

2023-11-21 09:59 UTC, ghost commented on src/main/java/org/kainos/ea/api/JobSpecService.java
> +        this.jobSpecDao = jobSpecDao;
gsdggdg``gd

2023-11-21 09:59 UTC, ghost commented on src/test/java/org/kainos/ea/integration/JobIntegrationTest.java
> +    String targetUrl = host + "/api/jobs/" + id;
End point just want to remain consistent with ` `

2023-11-21 09:59 UTC, ghost commented on src/test/java/org/kainos/ea/integration/JobIntegrationTest.java
> +    String targetUrl = host + "/api/jobs/" + id;
Same again here

2023-11-21 10:31 UTC, dmkainos approved these changes

2023-11-21 16:07 UTC, glenn-hamilton commented on sql-scripts/create-job-roles.sql
> +    ('Graphic Designer', 'https://kainossoftwareltd.sharepoint.com/people/SitePages/Career-Lattice.aspx');
These shouldn't all link the the `Career Lattice` but actual job specifications

2023-11-21 16:07 UTC, glenn-hamilton commented on sql-scripts/create-job-roles.sql
> +ADD COLUMN jobSpecUrl VARCHAR(255) DEFAULT 'https://kainossoftwareltd.sharepoint.com/people/SitePages/Career-Lattice.aspx';
Why set this as the default?

2023-11-21 16:07 UTC, glenn-hamilton commented on src/main/java/org/kainos/ea/client/JobNotFoundException.java
> +    return "Can't Get Roles";
Is this for Jobs or Roles?

2023-11-21 16:07 UTC, glenn-hamilton commented on src/main/java/org/kainos/ea/controller/JobController.java
>                .entity("Job roles retrieval error: " + e.getMessage())
It isn't part of this MR, but can you remove `Job roles retrieval error:`

2023-11-22 13:26 UTC, glenn-hamilton commented on src/test/java/org/kainos/ea/integration/JobIntegrationTest.java
> +    System.out.println("LOGGING HOST --> " + host);
This hasn't been removed 😢

2023-11-22 13:27 UTC, glenn-hamilton approved these changes

2023-11-23 11:33 UTC, merged